name: make-github-release-assets-darwin.yaml

on: [push]

# on:
#   push:
#     tags:
#       - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Publish binaries - darwin
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print env
        run: env
      - name: install create-dmg
        run: brew install create-dmg
      - name: Make executable file
        run: make darwin/amd64
      - name: Make a .dmg file
        # env:
        #   BUILD_VERSION: ${{ git describe --always --tags --abbrev=0 --dirty  | sed 's/v//' }}
        run: create-dmg  --app-drop-link 0 40 "Senzing-Tools-Application-Installer-$BUILD_VERSION.dmg"  "target/darwin-amd64/"
      - name: Upload versioned package to release assets
        # env:
        #   BUILD_VERSION: ${{ git describe --always --tags --abbrev=0 --dirty  | sed 's/v//' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "/Users/runner/work/explain/explain/Senzing-Tools-Application-Installer-$BUILD_VERSION.dmg"
          tag: ${{ github.ref }}
          overwrite: true
