name: make-github-release-assets-darwin.yaml

on: [push]

# on:
#   push:
#     tags:
#       - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Publish binaries - darwin
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install create-dmg
        run: brew install create-dmg
      - name: modify create-dmg
        run: sed -e "s|MOUNT_DIR/Applications|MOUNT_DIR/usr-local-bin|" -e "s|/Applications|/usr/local/bin|" /usr/local/bin/create-dmg > /usr/local/bin/create-dmg2;
      - name: Make executable file
        run: make darwin/amd64
      - name: Make a .dmg file
        run: |
          export BUILD_VERSION=$(git describe --always --tags --abbrev=0 --dirty  | sed 's/v//')
          create-dmg2 --app-drop-link 0 40 --version $BUILD_VERSION "explain-$BUILD_VERSION.dmg"  "target/darwin-amd64/"
      - name: Upload versioned package to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "/Users/runner/work/explain/explain/explain-*"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
